### PR TITLE
Release/1.2.1

### PR DESCRIPTION
**Pull request by elliotchance**
This change is [Reviewable](https://reviewable.io/reviews/elliotchance/collectionfactory/25)

### CODE REVIEW

**Comment by ngoctr** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CollectionFactory/NSObject+CollectionFactory.m, line 46 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN5nXJIMMHbiOnfV7M:-KTN5nXJIMMHbiOnfV7N:bea3cz8) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSObject+CollectionFactory.m#L46)):*
> ```objc
>             NSString *reason = [NSString stringWithFormat:
>                                 @"Unable to encode JSON: %@", e.reason]
>             @throw [NSException exceptionWithName:NSGenericException
> ```

I'd not recommend raising an exception, as we usually don't catch exception when calling some methods (if we do, we would catch the exception from [self valueForKey] and no need for the library to raise an exception). I'd recommend using a NSCAssert for this case, and return a nil dictionary in this case. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by ngoctr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CollectionFactory/NSURL+CollectionFactory.m, line 7 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN6Pen-L_6SjZ5RSmM:-KTN6Pen-L_6SjZ5RSmN:bh4f8oa) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSURL+CollectionFactory.m#L7)):*
> ```objc
> - (NSString *)JSONString
> {
>     return [self absoluteString];
> ```

I think it'd be `[[self absoluteString] JSONString]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by elliotchance** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[CollectionFactory/NSObject+CollectionFactory.m, line 46 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN5nXJIMMHbiOnfV7M:-KTNAnaNjFXDkq4FypIw:b-9lbsqs) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSObject+CollectionFactory.m#L46)):*
<details><summary><i>Previously, ngoctr (Ngoc Truong (Andy)) wrote…</i></summary>
> I'd not recommend raising an exception, as we usually don't catch exception when calling some methods (if we do, we would catch the exception from [self valueForKey] and no need for the library to raise an exception). I'd recommend using a NSCAssert for this case, and return a nil dictionary in this case. :-)
</details>
Originally I returned an empty dictionary but its very hard to debug because if you have 40 keys in an object you won't know which one actually caused the bug or why. Also it's dangerous to encoding something blinding that will cause a crash when you reverse it. An exception is appropriate in this case because it physically cannot carry out the task and need to tell you why (unrecoverable error).

---

*[CollectionFactory/NSURL+CollectionFactory.m, line 7 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN6Pen-L_6SjZ5RSmM:-KTNBmtJcTaFbVaFOy68:blzmybm) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSURL+CollectionFactory.m#L7)):*
<details><summary><i>Previously, ngoctr (Ngoc Truong (Andy)) wrote…</i></summary>
> I think it'd be `[[self absoluteString] JSONString]`
</details>
Yes, very good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by ngoctr** [comment]
Reviewed 2 of 3 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[CollectionFactory/NSObject+CollectionFactory.m, line 46 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN5nXJIMMHbiOnfV7M:-KTNC5QB7NIAvJ069a9-:b-6rhte6) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSObject+CollectionFactory.m#L46)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary>
> Originally I returned an empty dictionary but its very hard to debug because if you have 40 keys in an object you won't know which one actually caused the bug or why. Also it's dangerous to encoding something blinding that will cause a crash when you reverse it. An exception is appropriate in this case because it physically cannot carry out the task and need to tell you why (unrecoverable error).
</details>
If you use NSCAssert in this case, then it will stop the app when development. Return a nil dictionary just to help the app not crashed in a production build :-) An empty screen is better than a crash. Otherwise, we have to @try{} catch{} everytime we call object JSONString. Just my thoughts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by elliotchance** [comment]
Review status: 7 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[CollectionFactory/NSObject+CollectionFactory.m, line 46 at r1](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTN5nXJIMMHbiOnfV7M:-KTNn6K-pE6e4YnjcnYY:b-x1uc9d) ([raw file](https://github.com/elliotchance/collectionfactory/blob/86f5b263990ac7a1add0aa7001772635b1f071f9/CollectionFactory/NSObject+CollectionFactory.m#L46)):*
<details><summary><i>Previously, ngoctr (Ngoc Truong (Andy)) wrote…</i></summary>
> If you use NSCAssert in this case, then it will stop the app when development. Return a nil dictionary just to help the app not crashed in a production build :-) An empty screen is better than a crash. Otherwise, we have to @try{} catch{} everytime we call object JSONString. Just my thoughts.
</details>
Changed to NSError

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by ngoctr** [comment]
Reviewed 10 of 11 files at r3.
Review status: 17 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[CollectionFactory/NSArray+CollectionFactory.m, line 30 at r3](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTR9L7zEnprm4F1qhPD:-KTR9L7zEnprm4F1qhPE:bg1fg1l) ([raw file](https://github.com/elliotchance/collectionfactory/blob/47747b1c774131cd7342e6826ad0506934bd1cd6/CollectionFactory/NSArray+CollectionFactory.m#L30)):*
> ```objc
>     for (id item in self) {
>         NSString *string = [item JSONStringOrError:error];
>         if (string == nil) {
> ```

What if string is empty ""?

---

*[CollectionFactory/NSDictionary+CollectionFactory.m, line 26 at r3](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTR9XFlRM3Pxw1Wos5h:-KTR9XFmq49yk4-qgGiB:b-40zqyn) ([raw file](https://github.com/elliotchance/collectionfactory/blob/47747b1c774131cd7342e6826ad0506934bd1cd6/CollectionFactory/NSDictionary+CollectionFactory.m#L26)):*
> ```objc
> 
>         NSString *string = [item JSONStringOrError:error];
>         if (string == nil) {
> ```

Same as my comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by ngoctr** [comment]
Reviewed 1 of 11 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by elliotchance** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CollectionFactory/NSArray+CollectionFactory.m, line 30 at r3](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTR9L7zEnprm4F1qhPD:-KTRADtQhTIAU3ev8jb-:b-a6daap) ([raw file](https://github.com/elliotchance/collectionfactory/blob/47747b1c774131cd7342e6826ad0506934bd1cd6/CollectionFactory/NSArray+CollectionFactory.m#L30)):*
<details><summary><i>Previously, ngoctr (Ngoc Truong (Andy)) wrote…</i></summary>
> What if string is empty ""?
</details>
It can never be empty because a zero-length string is not a valid JSON value. `nil` is a specific return value if `JSONStringOrError` fails.

---

*[CollectionFactory/NSDictionary+CollectionFactory.m, line 26 at r3](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTR9XFlRM3Pxw1Wos5h:-KTRARWqX08P2a_X52Ml:bh7fw5p) ([raw file](https://github.com/elliotchance/collectionfactory/blob/47747b1c774131cd7342e6826ad0506934bd1cd6/CollectionFactory/NSDictionary+CollectionFactory.m#L26)):*
<details><summary><i>Previously, ngoctr (Ngoc Truong (Andy)) wrote…</i></summary>
> Same as my comment above
</details>
Same as my comment above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by ngoctr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CollectionFactory/NSArray+CollectionFactory.m, line 30 at r3](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25#-KTR9L7zEnprm4F1qhPD:-KTRBeKOshGNZE6NCl9f:bbw4nel) ([raw file](https://github.com/elliotchance/collectionfactory/blob/47747b1c774131cd7342e6826ad0506934bd1cd6/CollectionFactory/NSArray+CollectionFactory.m#L30)):*
<details><summary><i>Previously, elliotchance (Elliot Chance) wrote…</i></summary>
> It can never be empty because a zero-length string is not a valid JSON value. `nil` is a specific return value if `JSONStringOrError` fails.
</details>
Rightio

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Comment by elliotchance** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/elliotchance/collectionfactory/25)*

**Pull request merged**
